# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BpXNgHX7Zg4TPD6dBRlTWpIQMbyP21K
"""

import pandas as pd
from google.colab import files

# === Step 1: Upload Excel file ===
print("=== Upload File ===")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# === Step 2: Load dataset (Immersion) ===
df_raw = pd.read_excel(filename)

# Remove empty rows and unnamed columns
df_raw = df_raw.dropna(how='all')
df_raw = df_raw.loc[:, ~df_raw.columns.str.contains('^Unnamed')]
df_raw.columns = df_raw.columns.str.strip()

print("=== RAW DATASET (Before Cleaning) ===")
print(df_raw.head(20))   # Show first 20 rows

# === Step 3: RAW Data Dictionary (Profiling) ===
data_dict_raw = pd.DataFrame({
    "Column": df_raw.columns,
    "DataType": [str(df_raw[col].dtype) for col in df_raw.columns],
    "NonNullCount": [df_raw[col].notnull().sum() for col in df_raw.columns],
    "UniqueValues": [df_raw[col].nunique() for col in df_raw.columns]
})
print("\n=== RAW DATA DICTIONARY ===")
print(data_dict_raw)
print("Total rows (raw):", len(df_raw))

# Export raw dataset + raw dictionary
df_raw.to_excel("raw_dataset.xlsx", index=False)
data_dict_raw.to_excel("raw_data_dictionary.xlsx", index=False)

# === Step 4: Cleaning (Wrangling) ===
df_clean = df_raw.drop_duplicates()

# Standardize Gender
df_clean['Gender'] = df_clean['Gender'].astype(str).str.strip().str.capitalize()
df_clean['Gender'] = df_clean['Gender'].replace({'M':'Male','F':'Female'})

# Convert numeric columns
df_clean['Quantity'] = pd.to_numeric(df_clean['Quantity'], errors='coerce')
df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors='coerce')

# Remove negative prices
df_clean = df_clean[df_clean['Price'] >= 0]

# Parse DOB and Date
df_clean['DOB'] = pd.to_datetime(df_clean['DOB'], errors='coerce')
df_clean['Date'] = pd.to_datetime(df_clean['Date'], errors='coerce')

# Fill missing DOBs with median or default
if df_clean['DOB'].notna().any():
    median_dob = df_clean['DOB'].dropna().median()
    df_clean['DOB'] = df_clean['DOB'].fillna(median_dob)
else:
    df_clean['DOB'] = pd.Timestamp("1990-01-01")

# Calculate Age dynamically
today = pd.Timestamp.today()
df_clean['Age'] = (today - df_clean['DOB']).dt.days // 365

# Fill missing CustomerName/Email
df_clean['CustomerName'] = df_clean['CustomerName'].fillna("Unknown")
df_clean['Email'] = df_clean['Email'].fillna("Unknown")

print("\n=== CLEANED DATASET (After Cleaning) ===")
print(df_clean.head(20))   # Show first 20 rows

# === Step 5: CLEANED Data Dictionary (Deliverables) ===
data_dict_clean = pd.DataFrame({
    "Column": df_clean.columns,
    "DataType": [str(df_clean[col].dtype) for col in df_clean.columns],
    "NonNullCount": [df_clean[col].notnull().sum() for col in df_clean.columns],
    "UniqueValues": [df_clean[col].nunique() for col in df_clean.columns]
})
print("\n=== CLEANED DATA DICTIONARY ===")
print(data_dict_clean)
print("Total rows (cleaned):", len(df_clean))

# === Step 6: Export cleaned dataset (DOB formatted) ===
# Format DOB as string to avoid ########### in Excel
df_clean['DOB'] = df_clean['DOB'].dt.strftime('%Y-%m-%d')
df_clean['Date'] = df_clean['Date'].dt.strftime('%Y-%m-%d')

df_clean.to_excel("cleaned_dataset.xlsx", index=False)
data_dict_clean.to_excel("cleaned_data_dictionary.xlsx", index=False)

print("\nExcel files exported successfully!")

# === Step 7: Download all deliverables ===
files.download("raw_dataset.xlsx")
files.download("raw_data_dictionary.xlsx")
files.download("cleaned_dataset.xlsx")
files.download("cleaned_data_dictionary.xlsx")